---
title: "Nanopolish Methylation Validation"
author: "Scott Gigante"
date: "30/06/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(viridis)
library(data.table)
library(gridExtra)
library(forcats)
library(GenomicRanges)
```

## Load data

```{r dataloading_bisulfite}
load("../RData/bisulfite_df.RData")
```

```{r dataloading_nanopolish}
load("../RData/nanopolish_df.RData")
```

```{r datamerging}
nanopolish_df <- as.data.table(nanopolish_df)
bisulfite_df <- as.data.table(bisulfite_df)
setkey(bisulfite_df, chr, start, end)
meth_df <- foverlaps(nanopolish_df, bisulfite_df, type="any", nomatch=0) %>%
  na.omit() %>%
  dplyr::select(-i.start, -i.end) %>%
  dplyr::rename(percentMeth.nanopolish=i.percentMeth,
                percentMeth.bisulfite=percentMeth,
                coverage.bisulfite=coverage) %>%
  mutate(coverage.nanopolish=called_sites / num_cpgs_in_group) %>%
  dplyr::select(chr, start, end, 
                starts_with("percentMeth"), 
                starts_with("coverage"))
```

## Figure 1C

```{r plot_methylation}
meth_df %>%
  dplyr::select(starts_with("percentMeth")) %>%
  dplyr::rename(`Bisulfite`=percentMeth.bisulfite,
         `Nanopore`=percentMeth.nanopolish) %>%
  gather(variable, value) %>%
  ggplot(aes(x=value)) +
  facet_grid(variable~., scales="free") +
  geom_density() +
  labs(x=expression(paste("Methylation (", beta, ")")),
       y="Density") +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0))
ggsave("../plots/methylation_density.pdf")
```

## Figure 1D

```{r lm}
lm_fit <- lm(percentMeth.bisulfite ~ percentMeth.nanopolish, data=meth_df)
R2 <- 1 - (sum((lm_fit$residuals )^2) /
             sum((meth_df$percentMeth.bisulfite-mean(meth_df$percentMeth.bisulfite))^2))
R2
cor(meth_df$percentMeth.bisulfite, meth_df$percentMeth.nanopolish)**2
```

```{r}
min=1
thresh=0

for (i in seq(0.3, 0.5, by=0.01)) {
  error <- meth_df %>%
    filter(percentMeth.bisulfite!=0.5) %>%
    mutate(truth=percentMeth.bisulfite>0.5,
           call=percentMeth.nanopolish>i) %>%
    summarise(FP=sum(!truth & call),
              FN=sum(truth & !call))
  if ((error$FP+error$FN)/nrow(meth_df) < min) {
    min=(error$FP+error$FN)/nrow(meth_df)
    thresh = i
  }
}
print(min)
print(thresh)
```


```{r roc_guided_truth}
error_labels <- meth_df %>%
  filter(percentMeth.bisulfite!=0.5) %>%
  mutate(truth=percentMeth.bisulfite>0.5,
         call=percentMeth.nanopolish>round(thresh, digits=2)) %>%
  summarise(TP=sum(truth & call),
            FP=sum(!truth & call),
            TN=sum(!truth & !call),
            FN=sum(truth & !call))
FPR = round(error_labels$FP/(error_labels$FP + error_labels$TN)*100, digits=1)
FNR = round(error_labels$FN/(error_labels$FN + error_labels$TP)*100, digits=1)
error_labels <- error_labels %>%
  gather(variable, value) %>%
  mutate(percent=round(value/sum(value)*100),
         label=paste0(format(value, trim=TRUE, big.mark=","), " (", percent, "%)"))
error_labels$x = c(0.5+thresh/2, 0.5+thresh/2, thresh/2, thresh/2)
error_labels$y = c(0.75, 0.25, 0.25, 0.75)

p <- error_labels %>% ggplot(aes(x=x, y=y)) +
  geom_text(aes(label=label), hjust="center") +
  geom_vline(aes(xintercept=thresh)) +
  geom_vline(aes(xintercept=1)) +
  geom_vline(aes(xintercept=0)) +
  geom_hline(aes(yintercept=0.5)) +
  geom_hline(aes(yintercept=1)) +
  geom_hline(aes(yintercept=0)) +
  xlim(0, 1) + 
  ylim(0, 1) +
  stat_density_2d(data=meth_df %>% filter(percentMeth.bisulfite!=0.5), aes(x=percentMeth.nanopolish, y=percentMeth.bisulfite, fill = ..level.., alpha=..level..), geom='polygon', bins=500, show.legend = FALSE) +
  labs(x="Nanopore Methylation",
       y="Bisulfite Methylation") +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0))
p
ggsave("../plots/binned_site_concordance.pdf")
```
